language: ruby
dist: xenial
services:
  - postgresql
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
env:
  - ACTIVESUPPORT_MAJOR=5 SINATRA_MAJOR=2
  - ACTIVESUPPORT_MAJOR=6 SINATRA_MAJOR=2
jobs:
  exclude:
    - rvm: 2.4
      env: ACTIVESUPPORT_MAJOR=6 SINATRA_MAJOR=2
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
notifications:
  email: false
before_script:
  - createdb pliny-gem-test
script:
  - bundle exec rake
